apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: cluster-autoscaler
deploy:
  kubectl:
    manifests:
    - ./k8s/*
  helm:
    releases:
    - name: cluster-autoscaler
      remoteChart: autoscaler/cluster-autoscaler
      valuesFiles:
      - ./helm/values.yaml
      namespace: kube-system
      version: 9.19.2
      setValueTemplates:
        autoDiscovery.clusterName: '{{.CLUSTER_NAME}}'
        awsRegion: '{{.REGION}}'
      upgradeOnChange: true
