extraArgs:
  stderrthreshold: error
  skip-nodes-with-local-storage: false

image:
  tag: v1.23.1

rbac:
  serviceAccount:
    create: false
    name: cluster-autoscaler

replicaCount: 2

resources:
  limits:
    cpu: 100m
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 600Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

serviceMonitor:
  enabled: true
  namespace: monitoring

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
